kind: Deployment
apiVersion: apps/v1
metadata:
  name: datadog-log-tester
  namespace: default
  labels:
    app: datadog-log-tester
    tags.datadoghq.com/env: "poc"
    tags.datadoghq.com/service: "datadog-log-tester"
    tags.datadoghq.com/version: "v0.0.1"
  annotations:
    deployment.kubernetes.io/revision: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datadog-log-tester
  template:
    metadata:
      labels:
        app: datadog-log-tester
        tags.datadoghq.com/env: "poc"
        tags.datadoghq.com/service: "datadog-log-tester"
        tags.datadoghq.com/version: "v0.0.1"
    spec:
      containers:
        - name: datadog-log-tester
          image: alvarodelvalle/datadog-log-tester
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: DD_AGENT_SERVICE_PORT
              value: '8126'
            - name: STATS_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: STATS_PORT
              value: '8125'
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
